format: true
use-escaping: true
nullable-getter: false
synthetic-package: false

arb-dir: lib/l10n/translations
template-arb-file: checklist_en.arb

output-dir: lib/l10n/checklist_localizations
output-class: ChecklistLocalizations
output-localization-file: checklist_localizations.g.dart

untranslated-messages-file: lib/l10n/untranslated.txt