name: flutter_checklist
description: "A widget to display a checklist"

repository: https://github.com/maelchiotti/flutter_checklist
issue_tracker: https://github.com/maelchiotti/flutter_checklist/issues

version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_reorderable_list: ^1.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true